### ISSUE TITLE
Cyberfeeder card image

### ISSUE THREAD

**Issue by lostie** [zaroth/netrunner-cards-json#116]
Someone recently pointed out in a [Reddit Netrunner thread](https://www.reddit.com/r/Netrunner/comments/52rwjn/i_think_this_is_a_dumb_question_but_whats_up_with/) that the [current image appearing for Cyberfeeder](https://netrunnerdb.com/card_image/01005.png) does not match the actual card printed in the [Core Set](http://www.cardgamedb.com/forums/uploads/an/med_cyberfeeder-core.png)

Would it be possible to get the image updated with the correct print?

**Comment by Alsciende** [comment]
I don't have the correct image. The one on CGDB is bad quality.
