### ISSUE TITLE
Quarantine System's isn't showing in the deck builder.

### ISSUE THREAD

**Issue by Code-Echo-Chaser** [zaroth/netrunner-cards-json#170]
Not sure if this is the place for this but I've noticed that the new card from Daedalus Complex "Quarantine System" isn't showing in the deck builder. It's not listed in Weylands asset tab, nor does it appear when search for in the text box.

There is a card page for it which includes art so chances are it's on it's way but I thought I'd point this out in case it was a bug.

**Comment by gereons** [comment]
I think this rather belongs in NetrunnerDB: https://github.com/Alsciende/netrunnerdb/issues - the card data itself looks fine.

**Comment by Saintis** [comment]
This seems to be fixed now.
