### ISSUE TITLE
Q/Demand : Subtypes aka keywords

### ISSUE THREAD

**Issue by ANR-PeterPan** [zaroth/netrunner-cards-json#199]
Why dont we have a central file for Keyword-Translations like types.xx.json ?
Translation is (or should be^^) always the same.
Gray Ops = Graue Ops etc.

**Comment by Alsciende** [comment]
We don't have such a file because we don't have a table of all keywords. But I agree that it would be nice to have. We would need to refactor a few things though. At this point I don't think it's pertinent.
