### ISSUE TITLE
Adding Reviewers 

### ISSUE THREAD

**Issue by Alsciende** [zaroth/netrunner-cards-json#211]
Can you reviewers to the repo please, @zaroth ?

I'd like to request reviews from @JoelCFC25 , @gereons , @lostie if they're alright with it.

**Comment by gereons** [comment]
By all means, count me in!

**Comment by zaroth** [comment]
I'm not aware of a Reviewer role, but I added all three as Collaborators. This also means full push access, but I think it won't be a problem. ;-)

**Comment by JoelCFC25** [comment]
Joined. I don't know if it's a blessing or a curse, but typos have always just leaped off the page for me and I can't stop spotting them.
