### ISSUE TITLE
Remove blank/null values for optional properties

### ISSUE THREAD

**Issue by gereons** [zaroth/netrunner-cards-json#22]
Currently there are many places where optional properties like `keywords` or `flavor` are explicitly set to empty strings or `null`. Shouldn't those be simply left out? I'll provide a PR if you agree.

**Comment by Alsciende** [comment]
The translations data is going to be overwritten soon. I'll update it with your recent PR before doing the overwriting. I'll make sure nullable fields (`text`, `keywords`, `flavor`), when null, are not exported.
