### ISSUE TITLE
Cards missing illustrator and/or flavor text

### ISSUE THREAD

**Issue by zaroth** [zaroth/netrunner-cards-json#3]
Credit to OctoRex who originally submitted this list at https://bitbucket.org/alsciende/nrdb/issues/215/some-cards-missing-illustrator-and-flavour

    Advanced Concept Hopper
    Clairvoyant Monitor
    Corporate Town
    Cybernetics Division
    Dedication Ceremony
    Heritage Committee
    Interrupt 0
    Kala Ghoda Real TV
    Lab Dog
    Little Engine
    Lockdown
    Mumba Temple
    Mumbad City Grid
    Oaktown Grid
    Oaktown Renovation
    Quicksand
    Self-destruct Chips
    Vikram 1.0
    Analog Dreamers
    Artist Colony
    Chatterjee University
    Comet
    Crowbar
    High-stakes Job
    Immolation Script
    Jesminder Sareen
    Maya
    Mongoose
    Panchatantra
    Ramujan Reliant
    Run Amok
    Skulljack
    Street Magic
    Synthetic Blood
    Titanium Ribs
    Turntable

**Comment by zaroth** [comment]
cards from Chrome City are not missing illustrator anymore.

**Comment by JoelCFC25** [comment]
All the Kala Ghoda ones are in #5.

**Comment by zaroth** [comment]
So with this it seems we're done.
