### ISSUE TITLE
Normalization of cards with no flavor

### ISSUE THREAD

**Issue by zaroth** [zaroth/netrunner-cards-json#7]
Currently, some of the cards that have no flavor printed on cards have `flavor: ""`, some of them are lacking `flavor` at all. It'd be a good idea to normalize that.

Which one should it be? The first form shows us clearly that the flavor has been input to the DB, but is empty, why the second form is more succinct. If going with the first one, I think the best would be to go with nullable flavor, i.e. allow `flavor: null` and add a check that the strings are not empty.

**Comment by zaroth** [comment]
So in short, the option I'm leaning towards is:

- `flavor` is optional (spoiled cards with covered this part don't have it)
- cards with no flavor have `flavor: null`
- all other cards have `flavor: "non-empty string"`

If you give a thumbs up here, Alsciende, I can convert it.

**Comment by Alsciende** [comment]
I prefer the first option, flavor is optional and non-null, non-empty. Likewise for text (even if it's irrelevant for ANR).
