### ISSUE TITLE
Decks with Alliance cards show wrong influence under Chinese version

### ISSUE THREAD

**Issue by stimzh** [zaroth/netrunner-cards-json#72]
The faction Alliance cards (like Jeeves or Salem) still counts influence under Chinese version even if their rules are met, and switching back to other languages  they show correctly.

Besides, the Chinese part is down since last reboot, we hope it get restored soon, thanks!

**Comment by stimzh** [comment]
Hmm maybe I should post the issue at netrunnerdb repository instead of this, sorry.

**Comment by Alsciende** [comment]
Yes, indeed.
