### ISSUE TITLE
Cycle_code is unnecessary in card data

### ISSUE THREAD

**Issue by zaroth** [zaroth/netrunner-cards-json#8]
Since every card must belong to a pack, and every pack must belong to a cycle, I think listing a `cycle_code` in every card is redundant. I do understand that it may currently be needed by NRDB json importer due to how NRDB uses the data, but ideally it should be inferred from relationships between cycle, pack and card.

On the other hand, what could be added is a file `cycles.json` with each cycle number mapped to a human readable name, e.g. `{"cycle_code": "mumbad", "cycle_number": 10, "name": "Mumbad Cycle"}`.

**Comment by Alsciende** [comment]
Ok with me. No cycle_code in cards and no cycle_number in sets.

**Comment by zaroth** [comment]
Fixed by #9.
