### ISSUE TITLE
Adding 23 Seconds Scans

### ISSUE THREAD

**Issue by stimzh** [zaroth/netrunner-cards-json#83]
Here they are if you haven't collected them yet.

![23s 1](https://cloud.githubusercontent.com/assets/19706550/17140970/13906a16-537d-11e6-977c-05cd0c110016.png)
![23s 2](https://cloud.githubusercontent.com/assets/19706550/17140972/13f4de92-537d-11e6-991c-90886d53943d.png)
![23s 3](https://cloud.githubusercontent.com/assets/19706550/17140974/1459ef9e-537d-11e6-8e92-2477ceb883bd.png)
![23s 4](https://cloud.githubusercontent.com/assets/19706550/17140977/14a04750-537d-11e6-9d69-175e6d83e3c7.png)
![23s 5](https://cloud.githubusercontent.com/assets/19706550/17140976/14a044e4-537d-11e6-9611-72ca8fc57c57.png)
![23s 6](https://cloud.githubusercontent.com/assets/19706550/17140975/14a0473c-537d-11e6-8f99-4b1d869af22b.png)
![23s 7](https://cloud.githubusercontent.com/assets/19706550/17140978/14a4d55e-537d-11e6-8168-7fc9877e4ca3.png)
![23s 8](https://cloud.githubusercontent.com/assets/19706550/17140979/14a930c2-537d-11e6-8a79-9a29d9c84459.png)
![23s 9](https://cloud.githubusercontent.com/assets/19706550/17140980/14bf95d8-537d-11e6-8772-1941d7cf4ebb.png)
![23s 10](https://cloud.githubusercontent.com/assets/19706550/17140982/150afbcc-537d-11e6-98c1-e8082759e5c9.png)
![23s 11](https://cloud.githubusercontent.com/assets/19706550/17140981/1502beda-537d-11e6-9516-f40b415ef913.png)
![23s 12](https://cloud.githubusercontent.com/assets/19706550/17140983/150c4888-537d-11e6-9c4d-6db4d5d7848a.png)
![23s 13](https://cloud.githubusercontent.com/assets/19706550/17140984/150cdb68-537d-11e6-89ac-cdd0b9086659.png)
![23s 14](https://cloud.githubusercontent.com/assets/19706550/17140985/150fc40e-537d-11e6-81b4-854562ab78ea.png)
![23s 15](https://cloud.githubusercontent.com/assets/19706550/17140986/152612e0-537d-11e6-95cb-cfda21bf83e0.png)
![23s 16](https://cloud.githubusercontent.com/assets/19706550/17140988/1569dd0e-537d-11e6-9c71-3d88508babcf.png)
![23s 17](https://cloud.githubusercontent.com/assets/19706550/17140989/1571fe62-537d-11e6-9e3b-4d756be99765.png)
![23s 18](https://cloud.githubusercontent.com/assets/19706550/17140991/15746d00-537d-11e6-9493-228fa1f0f2e6.png)
![23s 19](https://cloud.githubusercontent.com/assets/19706550/17140990/15732a08-537d-11e6-8779-e479a3128afc.png)
![23s 20](https://cloud.githubusercontent.com/assets/19706550/17140992/157a8e10-537d-11e6-9eaf-9b55e2ebb12b.png)

**Comment by Alsciende** [comment]
Thanks a lot :)
